name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Some text here'
jobs: 
  job1:
    runs-on: ubuntu-latest
    outputs:
      varJob1Step1: ${{ steps.step11.outputs.varJob1Step1 }}
    steps:
      - name: Step 1 job1
        id: step11
        run: |
          
          GIT_COMMIT_ID="string1"
          ARC_COMMIT_ID="string1"

          if [ "$GIT_COMMIT_ID" == "$ARC_COMMIT_ID" ]; then 
            echo "VARJOB1STEP1=hello11111" >> $GITHUB_OUTPUT
          else
            echo "VARJOB1STEP1=hello22222" >> $GITHUB_OUTPUT
          fi
          
      - name: Step 2 job1
        id: step12
        run: echo ${{ steps.step11.outputs.varJob1Step1}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Step 1 job2
        id: step21
        run: echo ${{needs.job1.outputs.varJob1Step1}}
          
