name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Some text here'
jobs: 
  job1:
    runs-on: ubuntu-latest
    outputs:
      varJob1Step1: ${{ steps.step11.outputs.varJob1Step1 }}
    steps:
      - name: Step 1 job1
        id: step11
        run: echo "varJob1Step1=hello" >> $GITHUB_OUTPUT
      - name: Step 2 job1
        id: step12
        run: echo ${{ steps.step11.outputs.varJob1Step1}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Step 1 job2
        id: step21
        run: echo ${{needs.job1.outputs.varJob1Step1}}
          
